device_target: Ascend
dataset: "metal_nut"
dataset_path: "./dataset/metal_nut"
aug_dir: "./metal_aug"
distribute: False
model_arts: False
data_url: ""
train_url: ""
checkpoint_url: ""
cache_ckpt_file: "/cache/user-job-dir/ssim-ae/model.ckpt"

grayscale: False
do_aug: True
online_aug: False

# data_augment
augment_num: 10000
im_resize: 266
crop_size: 256
rotate_angle: 45.
p_ratate: 0.
p_horizontal_flip: 0.
p_vertical_flip: 0.

# train param
z_dim: 500
epochs: 200
batch_size: 128
lr: 2.0e-4
decay: 1.0e-5
flc: 32
stride: 32
load_ckpt_path: ""

# evaluation params
image_level: True
ssim_threshold: -1.0
l1_threshold: -1.0
bg_mask: "B"
img_suffix: ".png"
mask_suffix: "_mask.png"
percent: 99.996
run_eval: True
start_epoch: 160
eval_epochs: [1, 100, 150, 180, 185, 190, 195, 200]
interval: 1
checkpoint_path: "./train_metal_nut/checkpoint/best.ckpt"
save_dir: "./metal_nut_output"

---
# Help description for each configuration
device_target: "Target device type, available: [Ascend, GPU, CPU]"
dataset_path: "Dataset path for local"
aug_dir: "Augment path for local, default is {dataset_path}/train_patches"
distribute: "Whether enable distribute training"
model_arts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
cache_ckpt_file: "Checkpoint path in container."

grayscale: "Whether convert grayscale image."
do_aug: "Whether do augment when training."
z_dim: "Dimension of the latent space vector"
epochs: "Total training epochs"
batch_size: "Batch size for training and evaluation"
lr: "Learning rate when training."
decay: "Weight decay in optimizer"
flc: "Number of first hidden layer channels"
stride: "Step length of the sliding window"
ssim_threshold: "SSIM threshold for testing"
l1_threshold: "L1 threshold for testing"
bg_mask: "Background mask, B means black, W means white"
mask_suffix: "Ground truth suffix"
percent: "For estimating threshold based on valid positive samples"
run_eval: "Whether running evaluation when training"
interval: "Evaluation interval"
checkpoint_path: "Checkpoint path, If run_eval is True it will save the best ckpt, else the latest ckpt."
