# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: True


# Url for modelarts
data_url: ""
train_url: "./"
checkpoint_url: ""
local_data_url: "/cache/data"
local_train_url: "/cache/output"

# Path for local
run_distribute: False
enable_profiling: False
data_path: "./data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: "Ascend"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: "mindspore_cifar10.ckpt"

# ==============================================================================
# Training options

batch_size: 64
loss_scale: 1024
momentum: 0.9
weight_decay: 0.0001
epoch_size: 220
pretrain_epoch_size: 0
save_checkpoint: True
save_checkpoint_epochs: 1
keep_checkpoint_max: 5
warmup_epochs: 5
lr: 0.24
lr_decay_mode: "poly"
lr_init: 0.01
lr_end: 0.00001
lr_max: 0.1
lars_epsilon: 0.0
lars_coefficient: 0.001


dataset: "cifar10"
device_num: 8
pre_trained: ""
run_eval: False
eval_dataset_path: ""
dataset_sink_mode: True
parameter_server: False
filter_weight: False
save_best_ckpt: True
eval_start_epoch: 40
eval_interval: 1
enable_cache: False
cache_session_id: ""
mode_name: "GRAPH"
boost_mode: "O0"
conv_init: "XavierUniform"
dense_init: "TruncatedNormal"
train_image_size: 32
eval_image_size: 32

# Export options
device_id: 0
width: 32
height: 32
file_name: "ResidualAttentionNet92-cifar10"
file_format: "MINDIR"
ckpt_file: "mindspore_cifar10.ckpt"
network_dataset: "ResidualAttentionNet92-cifar10"

# postprocess resnet inference
result_path: ''
label_path: ''

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Dataset url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
load_path: "The location of checkpoint for obs"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
epoch_size: "Total training epochs."
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
