# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_fp16_gpu: False
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: "Ascend"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: "Unet3d-10-110.ckpt"

# ==============================================================================
# Training options
lr: 0.0005
batch_size: 1
epoch_size: 10
warmup_step: 120
warmup_ratio: 0.3
num_classes: 4
in_channels: 1
keep_checkpoint_max: 1
loss_scale: 256.0
roi_size : [224, 224, 96]
overlap: 0.25
min_val: -500
max_val: 1000
upper_limit: 5
lower_limit: 3

# Export options
device_id: 0
ckpt_file: "./checkpoint/Unet3d-10-110.ckpt"
file_name: "unet3d"
file_format: "MINDIR"

# 310 infer options
pre_result_path: "./preprocess_Result"
post_result_path: "./result_Files"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
enable_fp16_gpu: "Whether training on gpu with fp16, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
load_path: "The location of checkpoint for obs"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
epoch_size: "Total training epochs."
keep_checkpoint_max: "keep the last keep_checkpoint_max checkpoint"
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
