from .regnet_y_400mf import MindSporeModel as regnet_y_400mf_net
from .regnet_y_800mf import MindSporeModel  as regnet_y_800mf_net
from .regnet_y_1_6gf import MindSporeModel  as regnet_y_1_6gf_net
from .regnet_y_3_2gf import MindSporeModel  as regnet_y_3_2gf_net
from .regnet_y_8gf import MindSporeModel  as regnet_y_8gf_net
from .regnet_y_16gf import MindSporeModel  as regnet_y_16gf_net
from .regnet_y_32gf import MindSporeModel  as regnet_y_32gf_net
from .regnet_x_400mf import MindSporeModel  as regnet_x_400mf_net
from .regnet_x_800mf import MindSporeModel  as regnet_x_800mf_net
from .regnet_x_1_6gf import MindSporeModel  as regnet_x_1_6gf_net
from .regnet_x_3_2gf import MindSporeModel  as regnet_x_3_2gf_net
from .regnet_x_8gf import MindSporeModel  as regnet_x_8gf_net
from .regnet_x_16gf import MindSporeModel  as regnet_x_16gf_net
from .regnet_x_32gf import MindSporeModel  as regnet_x_32gf_net
